version: "3"
services:
  ethstat:
    image: rustwizard/ethstat-server
    build:
      context: .
      dockerfile: ./build/ethstat/server/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      ETH_SERVER_BIND: 0.0.0.0:8080
      ETH_SERVER_REQUEST_TTL: 3s
      ETH_SERVER_TRANSPORT: http
      ETH_PG_HOST: pg
      ETH_PG_PORT: 5432
      ETH_PG_USER: postgres
      ETH_PG_PASSWORD: postgres
      ETH_PG_DB: ethstat
      ETH_PG_SSL: disable
      ETH_PG_POOL_SIZE: 100

  pg:
    image: rustwizard/postgres:12
    build:
      context: build/pg
    container_name: pg
    restart: always
    volumes:
      - /opt/pg_data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ethstat
      PG_REP_USER: rep
      PG_REP_PASSWORD: 123456
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5432:5432"